stages:
- trigger
- build
- test
- deploy

variables:
  MDS_REGISTRY: "dockerv2-gsae-fm.gfx-assets.fm.intel.com/solutions"
  MDS_PROJECT_PATH: "vtt/sws/osgc/solutions/intel-media-delivery"
  http_proxy: "http://proxy-chain.intel.com:911"
  https_proxy: "http://proxy-chain.intel.com:911"
  no_proxy: ""

on_mr:
  stage: "trigger"
  script:
  - echo "Triggering MR-$CI_MERGE_REQUEST_IID build"
  - export # TODO delete me, that's debug print to check how we are getting triggerred
  only:
    refs:
    - merge_requests
    variables:
    - $CI_PROJECT_PATH == $MDS_PROJECT_PATH
    - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

on_merge:
  stage: "trigger"
  script:
  - echo "Triggering on-merge build"
  - export # TODO delete me, that's debug print to check how we are getting triggerred
  only:
    refs:
    - master
    variables:
    - $CI_PROJECT_PATH == $MDS_PROJECT_PATH

on_trigger:
  stage: "trigger"
  script:
  - echo "Building on external trigger event"
  - export # TODO delete me, that's debug print to check how we are getting triggerred
  only:
  - triggers

.trigger_rule:
  rules:
  - if: $CI_PROJECT_PATH == $MDS_PROJECT_PATH && $CI_COMMIT_REF_NAME == "master"
  - if: $CI_PROJECT_PATH == $MDS_PROJECT_PATH && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

.build_image:
  extends: .trigger_rule
  stage: "build"
  script:
  - tagname="$MDS_REGISTRY/intel-media-delivery/$SOLUTION/"
  - if [ -n "$CI_COMMIT_BRANCH" ]; then tagname+="$CI_COMMIT_BRANCH/stash:$CI_PIPELINE_ID"; fi
  - if [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]; then tagname+="$CI_MERGE_REQUEST_TARGET_BRANCH_NAME/"; fi
  - if [ -n "$CI_MERGE_REQUEST_IID" ]; then tagname+="mr:$CI_MERGE_REQUEST_IID"; fi
  - echo "Building $tagname docker image"
  - docker build
      $(env | grep -E '_proxy=' | sed 's/^/--build-arg /')
      --build-arg SOLUTION=$SOLUTION
      --no-cache
      --force-rm
      --network=host
      --file Dockerfile.ubuntu
      -t $tagname
      .
  - docker push $tagname
  - echo $tagname > tagname
  - docker rmi --force $(docker images -q $tagname | uniq)
  artifacts:
    paths:
    - tagname
  tags:
  - builder
  - ubuntu

.test_image:
  extends: .trigger_rule
  stage: "test"
  script:
  - tagname=$(cat tagname)
  - echo "Testing $tagname docker image"
  - docker pull $tagname
  - mkdir _logs
  - export MDS_IMAGE=$tagname
  - export MDS_LOGS=`pwd`/_logs
  - export MDS_DEMO=$SOLUTION
  - test_status=0
  - bats tests/*.bats || test_status=$?
  - docker rmi --force $(docker images -q $tagname | uniq)
  - if [ $test_status -ne 0 ]; then echo "Test failed"; false; fi
  artifacts:
    when: on_failure
    paths:
    - _logs/
    expire_in: 1 day
  tags:
  - ubuntu # bats is available here in our CI deployments
  - gen9

.deploy_image:
  extends: .trigger_rule
  stage: "deploy"
  script:
  - tagname=$(cat tagname)
  - if [[ $tagname =~ /stash:[0-9]*$ ]]; then
      deploytag="${tagname%stash*}/agama:latest";
      echo "Deploying $tagname as $deploytag";
      docker pull $tagname;
      docker tag $tagname $deploytag;
      docker push $deploytag;
      docker rmi --force
        $(docker images -q $tagname | uniq)
        $(docker images -q $deploytag | uniq);
    else
      echo "Already deployed on the build stage";
    fi
  tags:
  - builder
  - ubuntu

build:cdn:
  extends: .build_image
  variables:
    SOLUTION: cdn

build:edge:
  extends: .build_image
  variables:
    SOLUTION: edge

test:cdn:
  extends: .test_image
  variables:
    SOLUTION: cdn
  dependencies:
  - build:cdn

test:edge:
  extends: .test_image
  variables:
    SOLUTION: edge
  dependencies:
  - build:edge

deploy:cdn:
  extends: .deploy_image
  variables:
    SOLUTION: cdn
  dependencies:
  - build:cdn

deploy:edge:
  extends: .deploy_image
  variables:
    SOLUTION: edge
  dependencies:
  - build:edge
