#!/bin/bash
#
# Copyright (c) 2020 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# These 2 files should be provided by particular sample:
#  - /etc/demo.env contains environment variables needed to run a demo
#  - demo-setup contains container runtime setup steps
source /etc/demo.env

MDS_IGNORE_ERRORS=${MDS_IGNORE_ERRORS:-no}

if ! demo-setup; then
  if [[ "${MDS_IGNORE_ERRORS}" = "no" ]]; then
    echo "error: failed to setup demo" >&2
    exit -1
  else
    echo "warning: demo setup failed which means that demo won't run properly" >&2
    echo "warning: however you can look inside the container, check package versions" >&2
  fi
fi

if ! test -w $(pwd) && test -w /tmp; then
  echo "info: no write permissions to $(pwd) for current user (UID=$(id -u))" >&2
  echo "info:   changing to /tmp..." >&2
  cd /tmp
fi

"$@"
