name: cdn-agama-embargo-manual

on: 
  workflow_dispatch:
    inputs:
      agama_embargo_version:
        description: 'Agama version to use (ex.: agama-ci-embargo-517, agama-ci-prerelease-144)'
        required: true

jobs:
  build:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      flavor: ${{github.event.inputs.agama_embargo_version}}
      dockerfile: docker/ubuntu20.04/intel-gfx-embargo-vpl/Dockerfile.local
      pr_number: ${{github.event.pull_request.number}}
    secrets:
      SYS_M4_PASSWD: ${{ secrets.SYS_M4_PASSWD }}

  test-dg1:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'ON'
      on: dg1
      kernel: prelim

  test-dg2:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'ON'
      on: dg2
      kernel: dual-gpu

  deploy:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [build, test-dg1, test-dg2]
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      type: latest
      gta-asset-name: ${{github.event.inputs.agama_embargo_version}}

