name: cdn-agama-embargo

on: 
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-embargo.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-embargo.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy.yml'
  repository_dispatch:
    types: [build-embargo]

jobs:
  build:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      flavor: focal-embargo-untested
      dockerfile: docker/ubuntu20.04/intel-gfx-embargo-vpl/Dockerfile
      pr_number: ${{github.event.pull_request.number}}

  test-dg1:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'ON'
      on: dg1
      kernel: prelim

  test-dg2:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'ON'
      on: dg2
      kernel: dual-gpu

  deploy:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [test-dg1, test-dg2]
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      gta-asset-name: agama-embargo

