name: cdn-agama-public

on: 
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-public.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-public.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy.yml'
  repository_dispatch:
    types: [build-public]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      flavor: public
      dockerfile: docker/ubuntu20.04/intel-gfx/Dockerfile
      pr_number: ${{github.event.pull_request.number}}

  test-gen9:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'OFF'
      on: gen9
      kernel: linux

  test-dg1:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'OFF'
      on: dg1
      kernel: prelim

  deploy:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [test-gen9, test-dg1]
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      type: latest
      gta-asset-name: agama-public

