name: cdn-agama-devel

on: 
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-devel.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy-rolling.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-devel.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy-rolling.yml'
  repository_dispatch:
    types: [build-devel]

jobs:
  build-u2004:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      gfx_repo_key: 'https://repositories.gfxs.intel.com/internal/intel-graphics.key'
      gfx_repo: 'deb https://repositories.gfxs.intel.com/internal/ubuntu focal-devel-untested main'
      flavor: focal-devel-untested
      dockerfile: docker/ubuntu20.04/intel-gfx/Dockerfile

  test-dg1-u2004:
    needs: build-u2004
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build-u2004.outputs.image}}
      test_enctools: 'ON'
      on: dg1
      kernel: prelim

  test-atsm-u2004:
    needs: build-u2004
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build-u2004.outputs.image}}
      test_enctools: 'ON'
      on: atsm
      kernel: linux

  deploy-rolling-u2004:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [build-u2004, test-dg1-u2004, test-atsm-u2004]
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy-rolling.yml@master
    with:
      image: ${{needs.build-u2004.outputs.image}}
      gta-asset-name: agama-devel

  build-u2204:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      os: ubuntu:22.04
      gfx_repo_key: 'https://repositories.gfxs.intel.com/internal/intel-graphics.key'
      gfx_repo: 'deb https://repositories.gfxs.intel.com/internal/ubuntu jammy-devel-untested main'
      flavor: jammy-devel-untested
      dockerfile: docker/ubuntu22.04/intel-gfx/Dockerfile

  test-dg1-u2204:
    needs: build-u2204
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build-u2204.outputs.image}}
      test_enctools: 'ON'
      on: dg1
      kernel: prelim

  test-atsm-u2204:
    needs: build-u2204
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build-u2204.outputs.image}}
      test_enctools: 'ON'
      on: atsm
      kernel: linux

  deploy-rolling-u2204:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [build-u2204, test-dg1-u2204, test-atsm-u2204]
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy-rolling.yml@master
    with:
      image: ${{needs.build-u2204.outputs.image}}
      gta-asset-name: agama-devel

