name: cdn-agama-master

on: 
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-master.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy-rolling.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/cdn-agama-master.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy-rolling.yml'
  repository_dispatch:
    types: [build-master]

jobs:
  build:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      gfx_repo_key: 'https://repositories.gfxs.intel.com/internal/intel-graphics.key'
      gfx_repo: 'deb https://repositories.gfxs.intel.com/internal/ubuntu focal-untested main'
      flavor: focal-untested
      dockerfile: docker/ubuntu20.04/intel-gfx/Dockerfile
      pr_number: ${{github.event.pull_request.number}}

  test-gen9:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'OFF'
      on: gen9
      kernel: linux

  test-dg1:
    needs: build
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/test.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      test_enctools: 'ON'
      on: dg1
      kernel: prelim

  deploy-rolling:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [build, test-gen9, test-dg1]
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy-rolling.yml@master
    with:
      image: ${{needs.build.outputs.image}}
      gta-asset-name: agama-master

