name: deploy

on:
  workflow_call:
    inputs:
      repo:
        description: 'Which Github repo to clone?'
        required: false
        type: string
        default: ${{github.repository}}
      image:
        description: 'Which stash docker image to deploy?'
        required: true
        type: string
      gta-asset-name:
        description: 'Which gta-asset name to use?'
        required: true
        type: string

env:
  REGISTRY: dockerv2-gsae-fm.gfx-assets.fm.intel.com/solutions
  ARTIFACTORY: https://gfx-assets.fm.intel.com/artifactory
  ARTI_PATH: gfx-media-assets/media_solution/intel-media-delivery/cdn/master
  http_proxy: http://proxy-dmz.intel.com:912
  https_proxy: http://proxy-dmz.intel.com:912
  no_proxy: intel.com

jobs:
  deploy:
    runs-on: [self-hosted, osgc-solutions, ubuntu, builder]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{inputs.repo}}
    - run: |
        image=${{inputs.image}}
        name=${{inputs.gta-asset-name}}
        echo "Deploying $image ..."
        docker pull $image
        commit=$(git rev-parse --short $GITHUB_SHA)
        tag=$GITHUB_RUN_ID-$commit
        deploytag="${image%/stash*}/$name:$tag"
        echo "... as $deploytag ..."
        docker tag $image $deploytag
        docker push $deploytag
        docker rmi --force \
          $(docker images -q $image | uniq) \
          $(docker images -q $deploytag | uniq) || true
        echo "Posting artifactory asset ..."
        { \
          echo "{"; \
          echo "    \"pipeline\":\"${GITHUB_RUN_ID}\","; \
          echo "    \"commit_id\":\"${commit}\","; \
          echo "    \"docker_image\":\"${deploytag}\""; \
          echo "}"; \
        } > docker_image_info.json
        cat docker_image_info.json
        asset_name=${image%/stash*}
        asset_name=${asset_name#*intel-media-delivery/}
        gta-asset push --no-archive --root-url $ARTIFACTORY $ARTI_PATH/$asset_name $name $tag docker_image_info.json

