name: dkms

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'How to name docker (ex.: dkms-vX)?'
        required: true
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/dkms.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/dkms.yml'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test.yml'
    - '!.github/workflows/deploy.yml'

jobs:
  build-u2004:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      gfx_repo_key: ''
      gfx_repo: ''
      flavor: dkms
      dockerfile: docker/ubuntu20.04/dkms/Dockerfile

  build-u2204:
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/build.yml@master
    with:
      os: ubuntu:22.04
      gfx_repo_key: ''
      gfx_repo: ''
      flavor: dkms
      dockerfile: docker/ubuntu22.04/dkms/Dockerfile

  deploy-push-u2004:
    if: github.event_name == 'push'
    needs: build-u2004
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build-u2004.outputs.image}}
      gta-asset-name: dkms-u2004

  deploy-push-u2204:
    if: github.event_name == 'push'
    needs: build-u2204
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build-u2204.outputs.image}}
      gta-asset-name: dkms-u2204

  deploy-release-u2004:
    if: github.event_name == 'workflow_dispatch'
    needs: build-u2004
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build-u2004.outputs.image}}
      gta-asset-name: ${{github.event.inputs.name}}-u2004

  deploy-release-u2204:
    if: github.event_name == 'workflow_dispatch'
    needs: build-u2204
    uses: intel-innersource/containers.docker.gpu.media.intel-media-delivery/.github/workflows/deploy.yml@master
    with:
      image: ${{needs.build-u2204.outputs.image}}
      gta-asset-name: ${{github.event.inputs.name}}-u2204

