name: verify

on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/verify.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/verify.yml'

jobs:
  cmake:
    runs-on: [self-hosted, osgc-solutions, ubuntu-builder]
    steps:
    - uses: actions/checkout@v3
    - run: |
        cmake .
        make -j$(nproc)
        git diff --exit-code
